<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <div class="nav-search" id="nav-search">
                <span class="input-icon">
                    <input type="text" placeholder="url" class="nav-search-input" id="nav-search-input" autocomplete="off" name="url"/>
                    <i class="icon-search nav-search-icon"></i>
                </span>
    </div><!-- #nav-search -->
</div>

<div class="page-content">
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="table-responsive">
                <table id="listTable" class="table table-striped table-bordered table-hover">
                    <thead>
                        <th class="center">
                            <label>
                                <input type="checkbox" class="ace" />
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th>id</th>
                        <th>url</th>
                        <th>group</th>
                        <th>操作</th>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
<script src="app/js/list.js"></script>